**NumPy Practice Questions**

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

print(np.arange(1,11).sum())

[[1 2 3]
 [4 5 6]]
55


**How can you generate a random integer between 5 to 15**

In [ ]:
print(np.random.randint(5,15,size=(2,3)))

[[ 6  5 11]
 [ 7  6 11]]
23
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]


In [19]:
print(np.dot([2,3],[4,5]))# a and b are 1-d arrays

23


In [22]:
arr2 =np.array([[1,2,3],[4,5,6]])
print(arr2.flatten())
print(arr2.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [24]:
a =np.array([1,2,3])
b =np.array([1,3,4])
print(a==b)

[ True False False]
